### ISSUE TITLE
Names with forward slashes are not working

### ISSUE THREAD

**Issue by ghost** [hobbyquaker/hm2mqtt.js#13]
Hi

The Hometatic CCU2 an the former hm2mqtt addon allow Names like this:
"Waschkueche/Heizung/Schaltaktor"

The advantage was that they resultet in mqtt topics like
hm/status/Waschkueche/Heizung/Schaltaktor
so it was possible to subscribe to somethin like
hm/status/Waschkueche/#

hm2mqtt.js seems not fully support those names
while status messages are sen't as before, changing settings is not working
sending payload 0 to hm/set/Waschkueche/Heizung/Schaltaktor/STATE
results in:
0|hm2mqtt  | 2017-05-08 17:12:05.905 <error> mqtt < hm/set/Waschkueche/Heizung/Schaltaktor/STATE 0

can this be changed or do i have to rename my devices?

**Comment by hobbyquaker** [comment]
Hi! I have to think about this. Right now hm2mqtt.js accepts `hm/set/<channel>/<datapoint>` and `hm/set/<channel>/<paramset>/<datapoint>`. So this makes it difficult to distinguish between a set on e.g. the `MASTER` Paramset and a set on a channel with slashes in its name... Will try to find a solution that doesn't force you to rename your channels.

**Comment by hobbyquaker** [comment]
Sorry that it took so long ... Now you should be able to use slashes in Channel-, Variable- and Program-Names.

**Comment by ghost** [comment]
Super vielen Dank
Will test it as soon there are some rainy days :-)
