### ISSUE TITLE
PRESS_LONG message held back untill PRESS_LONG_RELEASE occurs

### ISSUE THREAD

**Issue by hesich** [hobbyquaker/hm2mqtt.js#21]
hm2mqtt version 2.2.2   node version 6.1.11

If I "long press" second button of a Homematic remote, I receive " immediately some "INSTALL_TEST" messages but only on "release button" the following pair is  received.

hm/status/HM-RC-8 OEQ0093861:2/PRESS_LONG
hm/status/HM-RC-8 OEQ0093861:2/PRESS_LONG_RELEASE

mqtt-spy log:
[hm2mqtt_msg_20171008.txt](https://github.com/hobbyquaker/hm2mqtt.js/files/1366967/hm2mqtt_msg_20171008.txt)
What is the purpose of the topic="hm/status/HM-RC-8 OEQ0093861:2/INSTALL_TEST" messages ??

thanks for this useful work and kind regards Hermann

**Comment by hobbyquaker** [comment]
Soweit ich weiss liefern leider nicht alle Geräte die `PRESS_CONT` Events (die normalerweise so ungefähr alle 250ms kommen solange man die Taste gedrückt hält). Sicher kann ich nur sagen dass die "alten" 4- und 19-Tasten Fernbedienungen sie senden, die nutze ich hier auch. ~~Dass `PRESS_LONG` erst am Ende vor dem `PRESS_LONG_RELEASE` kommt ist glaube ich normal.~~ Warum `INSTALL_TEST` gesendet kann ich Dir leider auch nicht beantworten, das weiss vmtl nur eQ-3...

**Comment by hobbyquaker** [comment]
Hier mal ein Auszug der Messages wenn ich eine Taste an einer alten 4-Tasten Fernbedienung drücke:

```
# mosquitto_sub -t 'hm/status/RC4:3/#' -v
hm/status/RC4:3/PRESS_LONG {"val":true,"ts":1507578256893,"lc":1507578220945,"hm":{"ADDRESS":"JEQ0143490:3"}}
hm/status/RC4:3/INSTALL_TEST {"val":true,"ts":1507578256893,"lc":1507578220959,"hm":{"ADDRESS":"JEQ0143490:3"}}
hm/status/RC4:3/PRESS_CONT {"val":true,"ts":1507578257144,"lc":1507578221185,"hm":{"ADDRESS":"JEQ0143490:3"}}
hm/status/RC4:3/PRESS_CONT {"val":true,"ts":1507578257395,"lc":1507578221185,"hm":{"ADDRESS":"JEQ0143490:3"}}
hm/status/RC4:3/PRESS_CONT {"val":true,"ts":1507578257658,"lc":1507578221185,"hm":{"ADDRESS":"JEQ0143490:3"}}
hm/status/RC4:3/PRESS_CONT {"val":true,"ts":1507578257899,"lc":1507578221185,"hm":{"ADDRESS":"JEQ0143490:3"}}
hm/status/RC4:3/PRESS_CONT {"val":true,"ts":1507578258153,"lc":1507578221185,"hm":{"ADDRESS":"JEQ0143490:3"}}
hm/status/RC4:3/PRESS_CONT {"val":true,"ts":1507578258408,"lc":1507578221185,"hm":{"ADDRESS":"JEQ0143490:3"}}
hm/status/RC4:3/INSTALL_TEST {"val":true,"ts":1507578258408,"lc":1507578220959,"hm":{"ADDRESS":"JEQ0143490:3"}}
hm/status/RC4:3/PRESS_CONT {"val":true,"ts":1507578258669,"lc":1507578221185,"hm":{"ADDRESS":"JEQ0143490:3"}}
hm/status/RC4:3/PRESS_CONT {"val":true,"ts":1507578258911,"lc":1507578221185,"hm":{"ADDRESS":"JEQ0143490:3"}}
hm/status/RC4:3/PRESS_CONT {"val":true,"ts":1507578259165,"lc":1507578221185,"hm":{"ADDRESS":"JEQ0143490:3"}}
hm/status/RC4:3/PRESS_LONG_RELEASE {"val":true,"ts":1507578259166,"lc":1507578222447,"hm":{"ADDRESS":"JEQ0143490:3"}}
```

**Comment by hobbyquaker** [comment]
Ah - mir ist noch was eingefallen. Es kann sein dass Deinem Device ein "reportValueUsage" fehlt. Falls Du eine CCU benutzt versuch mal "Dummy-Programme" anzulegen die auf Tastendruck reagieren, den "Dann-Teil" kannst einfach leer lassen.

**Comment by hesich** [comment]
Ein "dummy-01" Programm hat keine Änderung des Verhaltens gebracht.
A einem anderen Standort: hm2mqtt 1.0.7 , node.js 6.11.1, RaspMmatic 2.27.8.20170620, Node-RED version: v0.17.5,  Linux 4.9.35-v7+ arm LE verhält es sich gleich.
Der Intervall der "INSTALL_TEST" könnte einem "PRESS_CONT" gleichkommen.
Die Funktionsweise Deiner "alten" Fernbedienung wäre genau das Richtige gewesen.
Ich werde einen neuen Handsender https://www.elv.ch/controller.aspx?cid=726&detail=57169 bestellen, und prüfen wie die erwähnte "Dimm-funktion" umgesetzt wurde.

[hm_button_02.txt](https://github.com/hobbyquaker/hm2mqtt.js/files/1374969/hm_button_02.txt)
![hm_button_01](https://user-images.githubusercontent.com/11912544/31432362-bf7cf646-ae76-11e7-9ba1-2394a1bf3a26.png)
