### ISSUE TITLE
Usage with Homematic IP Access Point

### ISSUE THREAD

**Issue by krystianity** [hobbyquaker/hm2mqtt.js#25]
Hi @hobbyquaker  you are saying in the README that the bridge also works with Homematic IP, but when passing the IP of the access point as ccu parameter the connection attempts run into timeouts. I have checked the ports on the device and it seems like port 2010 is not open.

Do I have run an additional CCU2 just to use that as bridge to connect to the Homematic IP access point? Why didnt eq3 offer any API option for the Homematic IP Access Point?

**Comment by hobbyquaker** [comment]
Using hm2mqtt.js with the Hm-IP Access Point is not possible, you need a CCU2 (or RaspberyMatic or Yahm or piVCCU). Mind that you can use your HmIP devices with either a CCU2 _or_ an Access Point, using both is not possible.

If you want to use the Access Point (I strongly discourage to use that thing, it's "cloud" dependent and you can't control your devices if your Internet connection or the eQ-3 Servers are down) this unofficial, reversed engineered python wrapper for the HmIP-AccessPoint-Cloud-API could be interesting for you: https://github.com/coreGreenberet/homematicip-rest-api

**Comment by krystianity** [comment]
Thanks for the reply @hobbyquaker , I was thinking about porting homematicip-rest-api to Node.js but the cloud dependency to eq3's bad servers is quite sad.. - I just ordered a CCU2 .. will throw away the Access Point.
