### ISSUE TITLE
CONTROL_MODE not writeable

### ISSUE THREAD

**Issue by the-s0urce** [hobbyquaker/hm2mqtt.js#27]
Hi, why is CONTROL_MODE not writeable?

**Comment by hobbyquaker** [comment]
This can only be answered by eQ-3 ;-)
If you want to change `CONTROL_MODE` of a `HM-CC-RT-DN` or a `HM-TC-IT-WM-W-EU` you have to write on the Datapoints `MANU_MODE `, `AUTO_MODE`, ...
See Documentation of Datapoints here: http://www.eq-3.de/Downloads/eq3/download%20bereich/hm_web_ui_doku/hm_devices_Endkunden.pdf

**Comment by the-s0urce** [comment]
Thank you for the hint, and for all your work.
