### ISSUE TITLE
Help needed with PM2

### ISSUE THREAD

**Issue by chrispi68** [hobbyquaker/hm2mqtt.js#31]
Hi,

I am able to run hm2mqtt without any problems via this call:

hm2mqtt --disable-rega --mqtt-url mqtt://192.168.1.8 --name HomeMatic_CCU --ccu-address 192.168.1.24 --verbosity debug

But it does not work with PM2:

sudo pm2 start hm2mqtt --node-args="--disable-rega --mqtt-url mqtt://192.168.1.8 --name HomeMatic_CCU --ccu-address 192.168.1.24 --verbosity debug"

The error message is 
node: bad option: --mqtt-url
node: bad option: --disable-rega

When I remove these two arguments, the --name argument shows up in the error message.

I tried a lot of different variants but without any success.

I use a fresh install of hm2mqtt, Ubuntu 18.04 and PM2.

I am grateful for any help

Christoph

**Comment by hobbyquaker** [comment]
Try it with
```
pm2 start hm2mqtt -- --disable-rega --mqtt-url mqtt://192.168.1.8 --name HomeMatic_CCU --ccu-address 192.168.1.24 --verbosity debug
```

(The `--` separates pm2 and hm2mqtt options)

**Comment by chrispi68** [comment]
This worked! Thank you very much.

Grüße aus Düsseldorf,
Christoph
