### ISSUE TITLE
GET

### ISSUE THREAD

**Issue by hobbyquaker** [hobbyquaker/hm2mqtt.js#5]
Active Get. Does anyone want this? I don't need it.

**Comment by hobbyquaker** [comment]
already possible via rpc command, question is if a more convenient way (mqtt topic /get/) would make sense

**Comment by maplesteve** [comment]
@hobbyquaker  Could you point me to an example on how to send the correct get command via mqtt? I understand that e.g. getValue wants some parameters, but don't understand how to pass them via mqtt. Thanks!
